spring:
  application:
    name: pictogram-translator
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/pictograms}

server:
  port: 8080

arasaac:
  image-base-url: https://static.arasaac.org/pictograms
